<../mkconfig

LIB=/usr/pkg/lib/libv.a

OFILES=getpass.$O\
	tty.$O\
	rand.$O\
	nrand.$O\
	getfields.$O\
	min.$O\
	max.$O\
	error.$O\
	nap.$O

<../mksyslib

CFLAGS=$CFLAGS -c

%.$O:	$FAMILY/%.c
	$CC $CFLAGS $prereq
