<../mkconfig

LIB=/usr/pkg/lib/lib9.a
OFILES=errstr.$O\
	bind.$O\
	mount.$O\
	unmount.$O\
	rfork.$O\
	segattach.$O\
	segdetach.$O\
	segflush.$O\
	segfree.$O\
	setmalloctag.$O\
	rendezvous.$O\
	getfcr.$O\
	getcallerpc.$O\

<../mksyslib

CFLAGS=-c $CFLAGS -D_PLAN9_SOURCE

%.$O:	$objtype/%.s
	$AS -o $target $prereq

%.$O:	$objtype/%.c
	$CC $CFLAGS $prereq
