<../../mkconfig
LIB=/usr/pkg/lib/libc.a
OFILES=\
	asin.$O\
	atan.$O\
	atan2.$O\
	erf.$O\
	exp.$O\
	fabs.$O\
	floor.$O\
	fmod.$O\
	gamma.$O\
	hypot.$O\
	j0.$O\
	j1.$O\
	jn.$O\
	log.$O\
	pow.$O\
	sin.$O\
	sinh.$O\
	tan.$O\
	tanh.$O\

<../../mksyslib

CFLAGS=$CFLAGS -c
